name: "Build Terraform Module"
description: "Various validations and formatting of terraform module"
inputs:
  path:
    description: "The path of the module to build."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup-Terraform
      uses: hashicorp/setup-terraform@v3
      if: ${{ hashFiles(format('{0}/main.tf', inputs.path)) != '' }}
      with:
        terraform_version: 1.9.4
    - name: Terraform-Init
      if: ${{ hashFiles(format('{0}/main.tf', inputs.path)) != '' }}
      working-directory: ${{ inputs.path }}
      run: terraform init
      shell: bash
    - name: Terraform-Validation
      if: ${{ hashFiles(format('{0}/main.tf', inputs.path)) != '' }}
      working-directory: ${{ inputs.path }}
      run: terraform validate
      shell: bash
    - name: Terraform-Format-Check
      if: ${{ hashFiles(format('{0}/main.tf', inputs.path)) != '' }}
      working-directory: ${{ inputs.path }}
      run: terraform fmt -check
      shell: bash
    # - name: Terraform-Test
    #   working-directory: ${{ inputs.path }}
    #   # only do tf test if there's a tests/ folder... 
    #   if: ${{ hashFiles('./tests') != '' }}
    #   run: terraform test
    #   shell: bash

