name: "Build Terraform Module"
description: "Various validations and formatting of terraform module"
inputs:
  path:
    description: "The path of the module to build."
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup-Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.4
    - name: Terraform-Format-Check
      working-directory: ${{ inputs.path }}
      run: terraform fmt -check -diff
      shell: bash
    - name: Terraform-Init
      working-directory: ${{ inputs.path }}
      run: terraform init -input=false
      shell: bash
    - name: Terraform-Validation
      working-directory: ${{ inputs.path }}
      run: terraform validate
      shell: bash
    # - name: Terraform-Test
    #   working-directory: ${{ inputs.path }}
    #   # only do tf test if there's a tests/ folder... 
    #   if: ${{ hashFiles('./tests') != '' }}
    #   run: terraform test
    #   shell: bash

