name: "Lookup Account ID from Name"
description: "Given a friendly name for an organizational account, finds it's corresponding account id."
inputs:
  env:
    description: "The environment we want to deploy into."
    required: true
outputs:
  project-context: 
    description: "The full Project Context"
    value: ${{ steps.get-project-context.outputs.project-context }}
  tooling-account: 
    description: "The ID of the Tooling Account"
    value: ${{ steps.get-project-context.outputs.tooling-account }}
  account:
    description: "The ID of the Account assigned to the current environment"
    value: ${{ steps.get-project-context.outputs.account }}
  project:
    description: "The name of the Project"
    value: ${{ steps.get-project-context.outputs.project }}
runs:
  using: composite
  steps:
    - name: Apt-Install-AWS-CLI
      run: |
        sudo apt-get install awscli
        aws --version
        aws sts get-caller-identity
      shell: bash
    - name: Get-Project-Context
      id: get-project-context
      run: |
        PROJECT_CONTEXT=$(aws ssm get-parameter --name project_context --query "Parameter.Value" --output text)
        echo "project-context=${PROJECT_CONTEXT}"
        TOOLING_ACCOUNT=$(echo ${PROJECT_CONTEXT} | yq -r .accounts.tooling)
        ACCOUNT=$(echo ${PROJECT_CONTEXT} | yq -r .accounts.${{ inputs.env }})
        PROJECT=$(echo ${PROJECT_CONTEXT} | yq -r .project)
        echo "project-context=${PROJECT_CONTEXT}" >> "$GITHUB_OUTPUT"
        echo "tooling-account=${TOOLING_ACCOUNT}" >> "$GITHUB_OUTPUT"
        echo "account=${ACCOUNT}" >> "$GITHUB_OUTPUT"
        echo "project=${PROJECT}" >> "$GITHUB_OUTPUT"
      shell: bash
    