name: "NPM Build"
description: "Runs npm build script"
inputs:
  path:
    description: "The path to build from."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Setup-Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: NPM-CI
      run: npm ci
      shell: bash
    - name: NPM-Build
      working-directory: ${{ inputs.path }}
      run: npm run build
      shell: bash
    # - name: NPM-Test
    #   run: npm run test
    #   shell: bash