name: Build API
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: "./"

jobs:
  Build-API:
    runs-on: ubuntu-latest
    steps:
      - name: Git-Clone
        uses: actions/checkout@v4
      - name: NPM-Build
        uses: jfdi-dev/pipelines/.github/actions/npm-build@main
        with:
          path: ${{ inputs.path }}
      - name: Show-Dist
        working-directory: ${{ inputs.path }}
        run: ls -laR .build/
        shell: bash
      - name: Save-API
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: ${{ format('{0}/.build/', inputs.path) }}
          include-hidden-files: true
          if-no-files-found: error
