name: Build Static Site
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: "./"
      dir:
        type: string
        required: false
        default: ".dist/"

jobs:
  Build-Static-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Git-Clone
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: NPM-Build
        uses: jfdi-dev/pipelines/.github/actions/npm-build@main
        with:
          path: ${{ inputs.path }}
      - name: Show-Dist
        working-directory: ${{ inputs.path }}
        run: ls -laR ${{ inputs.dir }}
        shell: bash
      - name: Save-Static-Files
        uses: actions/upload-artifact@v4
        with:
          name: static-files
          path: ${{ format('{0}/{1}', inputs.path, inputs.dir) }}
          include-hidden-files: true
          if-no-files-found: error
