name: Create Deployment Role
on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      env:
        required: true
        type: string
      # account:
      #   required: true
      #   type: string
      # project:
      #   required: true
      #   type: string
      # artifact:
      #   required: true
      #   type: string
    secrets:
      aws-ci-role-arn:
        required: true
      # tooling-account:
      #   required: true

jobs:
  Create-Deployment-Role:
    runs-on: ubuntu-latest
    steps:
      - name: Git-Clone
        uses: actions/checkout@v4
      - name: On-AWS
        id: aws
        uses: jfdi-dev/pipelines/.github/actions/on-aws@main
        with:
          region: ${{ inputs.region }}
          ci-role-arn: ${{ secrets.aws-ci-role-arn }}
          env: ${{ inputs.env }}
          artifact: iam
      - name: Run-Terraform
        uses: jfdi-dev/pipelines/.github/actions/run-terraform@main
        id: run-terraform
        with:
          dir: deployment-role/
          region: ${{ inputs.region }}
          project-context: ${{ steps.aws.outputs.project-context }}
          # tooling-account: ${{ steps.aws.outputs.project-context.tooling-account }}
          # project: ${{ steps.aws.outputs.project-context.project }}
          # account: ${{ steps.aws.outputs.project-context.account }}
          # state: ${{ steps.aws.outputs.project-context.terraform.state }}
          # locks: ${{ steps.aws.outputs.project-context.terraform.locks }}
