name: IAC Build Pipeline
on:
  workflow_call:

jobs:
  Gather-Modules:
    runs-on: ubuntu-latest
    outputs:
      module-dirs: ${{ steps.list-directories.outputs.module-dirs }}
    steps:
      - name: Git-Clone
        uses: actions/checkout@v4
      - name: List-Directories
        id: list-directories
        run: |
          MODULE_DIRS=$(echo '[' $(find . -not -path '*/[@.]*' -type d  -printf "\"%p\"," | sed 's/,$//') ']' | jq -c)
          echo "module-dirs=${MODULE_DIRS}" >> $GITHUB_OUTPUT
        shell: bash
  Build-And-Test-Modules:
    runs-on: ubuntu-latest
    needs:
      - Gather-Modules
    strategy:
      matrix:
        module: ${{ fromJSON(needs.Gather-Modules.outputs.module-dirs) }}
      fail-fast: false
    steps:
      - name: Git-Clone
        uses: actions/checkout@v4
      - name: Build-Modules
        uses: jfdi-dev/pipelines/.github/actions/build-terraform-module@main
        with:
          path: ${{ matrix.module }}
