name: IAC Build Pipeline
on:
  workflow_call:

jobs:
  Gather-Modules:
    runs-on: ubuntu-latest
    outputs:
      module-dirs: ${{ steps.list-directories.outputs.module-dirs }}
    steps:
      - name: Git-Clone
        uses: actions/checkout@v4
      - name: List-Directories
        id: list-directories
        # Grim line-noise to find names of directories which contain a main.tf file. ie: directories which contain terraform modules...
        run: |
          MODULE_DIRS=$(echo '[' $(find . -type f -name '*\main.tf*' | sed -r 's|/[^/]+$||' | sort | uniq | sed -e 's/^\|$/"/g' | paste -d, -s -) ']' | jq -c)
          echo "module-dirs=${MODULE_DIRS}" >> $GITHUB_OUTPUT
        shell: bash
  Validate-Module:
    runs-on: ubuntu-latest
    needs:
      - Gather-Modules
    strategy:
      matrix:
        module: ${{ fromJSON(needs.Gather-Modules.outputs.module-dirs) }}
      fail-fast: false
    steps:
      - name: Git-Clone
        uses: actions/checkout@v4
      - name: Build-Modules
        uses: jfdi-dev/pipelines/.github/actions/build-terraform-module@main
        # Only if the main.tf really does exist
        if: ${{ hashFiles(format('{0}/main.tf', matrix.module)) != '' }}
        with:
          path: ${{ matrix.module }}
