name: Static Site Pipeline
on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
    secrets:
      aws-ci-role-arn:
        required: true

jobs:
  Store-Manifest:
    uses: jfdi-dev/pipelines/.github/workflows/store-manifest.yml@main
    with:
      module: www
  Build-Static-Site:
    uses: jfdi-dev/pipelines/.github/workflows/build-static-site.yml@main
  Dev-Deploy-Static-Site:
    uses: jfdi-dev/pipelines/.github/workflows/deploy-static-site.yml@main
    needs:
      - Store-Manifest
      - Build-Static-Site
    with:
      region: ${{ inputs.region }}
      env: dev
    secrets:
      aws-ci-role-arn: ${{ secrets.aws-ci-role-arn }}
  # Test-Deploy-Static-Site:
  #   uses: jfdi-dev/pipelines/.github/workflows/create-deployment-role.yml@main
  #   with:
  #     region: ${{ inputs.region }}
  #     env: test
  #   secrets:
  #     ci-role-arn: ${{ secrets.aws-ci-role-arn }}
  # Prod-Deploy-Static-Site:
  #   uses: jfdi-dev/pipelines/.github/workflows/create-deployment-role.yml@main
  #   with:
  #     region: ${{ inputs.region }}
  #     env: prod
  #   secrets:
  #     ci-role-arn: ${{ secrets.aws-ci-role-arn }}
