name: Store Manifest
on:
  workflow_call:

jobs:
  Build-Static-Site:
    runs-on: ubuntu-latest
    steps:
      - name: Git-Clone
        uses: actions/checkout@v4
      - name: Save-Manifest
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: manifest.yml
